In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("devices_20210129_1621.csv", usecols = ['mdt_id','vehicle_id', 'list_of_app', 'rpt_time']) 

#Manually filter last report by latest date and remove the duplicated entries that has an older date
df['rpt_time'] =pd.to_datetime(df.rpt_time)
df.sort_values('rpt_time', ascending = False , inplace = True)

#trim vehicle plate whitespace
df['vehicle_id'] = df.vehicle_id.str.replace(' ', '')

df.set_index('vehicle_id')

#drop duplicated plate number
df.drop_duplicates(subset ="vehicle_id", 
                     keep = "first", inplace = True) 

#import vehicle master list
df_v = pd.read_csv("SMRT-master.csv", index_col = 'vehicle_id') 

df_smrt = pd.merge(df,  
                     df_v,  
                     on ='vehicle_id',  
                     how ='right') 
df_smrt

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
0,SHB786K ID,SHB786K,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 16:35:19,Hired
1,864403045571834,SHF184B,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 16:29:55,Hired
2,861075023920630,SHC4533S,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 16:17:08,Unhired
3,861075024188252,SHB5734C,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 14:58:44,Hired
4,861075023927445,SHC4759H,"com.ucast.blackbox:1.0.1014.201027_RC,com.grab...",2021-12-01 14:18:28,Hired
...,...,...,...,...,...
1795,NaN,SHF484K,NaN,NaT,Unhired
1796,NaN,SHF493J,NaN,NaT,Unhired
1797,NaN,SHF497Z,NaN,NaT,Unhired
1798,NaN,SHF498X,NaN,NaT,Unhired
1799,NaN,SHF499T,NaN,NaT,Unhired

In [2]:
#hired & on v28
df_smrt[(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) & (df_smrt['Hired Status'] == 'Hired')]

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
0,SHB786K ID,SHB786K,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 16:35:19,Hired
1,864403045571834,SHF184B,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 16:29:55,Hired
3,861075024188252,SHB5734C,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 14:58:44,Hired
5,861075024179046,SHB5206K,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-12-01 13:50:00,Hired
8,861075024176034,SHF77C,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-11-01 15:43:26,Hired
...,...,...,...,...,...
1512,861075024187569,SHF412T,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-01-13 15:03:45,Hired
1514,861075023937188,SHC4655Z,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-01-13 13:10:41,Hired
1515,864403045569226,SHB5364L,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2021-01-13 11:54:07,Hired
1525,861075023926603,SHC4777E,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2020-12-29 14:43:38,Hired
1526,861075024176091,SHB903P,"com.ucast.blackbox:1.0.1028.201216_RC,com.grab...",2020-12-28 14:07:33,Hired

In [3]:
#hired & not on v28
df_smrt[~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) & (df_smrt['Hired Status'] == 'Hired')]

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
4,861075023927445,SHC4759H,"com.ucast.blackbox:1.0.1014.201027_RC,com.grab...",2021-12-01 14:18:28,Hired
6,861075023928716,SHF59E,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-12-01 10:24:19,Hired
9,861075024164378,SHB959D,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-11-01 14:34:40,Hired
20,861075023931660,SHD6277M,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-08-01 22:41:25,Hired
21,861075024163974,SHD6334G,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-08-01 20:13:51,Hired
...,...,...,...,...,...
1670,NaN,SHF2T,NaN,NaT,Hired
1671,NaN,SHF339Y,NaN,NaT,Hired
1672,NaN,SHF365X,NaN,NaT,Hired
1673,NaN,SHF477G,NaN,NaT,Hired
1674,NaN,SHF74K,NaN,NaT,Hired

In [4]:
#hired & not on v28 and has 2 ota client
df_smrt[~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) 
        & (df_smrt['Hired Status'] == 'Hired') 
        & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdmv2:1.0.15', na=False))
        & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdm:1', na=False))
       ]

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
41,861075024188369,SHB5904D,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-05-01 15:41:33,Hired
44,861075023937907,SHC4703T,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-05-01 01:30:28,Hired
57,861075023924301,SHD6202D,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-29 16:21:15,Hired
74,861075024186454,SHB5705L,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-01-29 16:21:04,Hired
93,861075023934417,SHF30L,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-01-29 16:20:48,Hired
...,...,...,...,...,...
1467,861075023925027,SHC4022A,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-19 11:04:23,Hired
1500,861075024188377,SHB1728Y,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-01-14 15:28:57,Hired
1511,861075024194466,SHF209P,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-01-13 16:11:58,Hired
1513,861075024165706,SHB159X,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-13 14:29:52,Hired
1532,861075024176752,SHB5738S,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2020-12-25 04:32:10,Hired

In [5]:
#hired & not on v28 and ota client v11
df_smrt[~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) 
        & (df_smrt['Hired Status'] == 'Hired') 
        & ~(df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdmv2:1.0.15', na=False))
        & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdm:1.0.11', na=False))
       ]

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
4,861075023927445,SHC4759H,"com.ucast.blackbox:1.0.1014.201027_RC,com.grab...",2021-12-01 14:18:28,Hired
6,861075023928716,SHF59E,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-12-01 10:24:19,Hired
9,861075024164378,SHB959D,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-11-01 14:34:40,Hired
21,861075024163974,SHD6334G,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-08-01 20:13:51,Hired
32,861075024187866,SHB457K,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2021-07-01 12:04:09,Hired
...,...,...,...,...,...
1534,861075024163883,SHB5586M,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2020-12-24 08:05:55,Hired
1549,861075024182909,SHD6188L,"com.ucast.blackbox:1.0.1027.201209_RC,com.grab...",2020-12-16 17:19:54,Hired
1551,861075023922321,SHB1273S,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2020-12-16 05:45:37,Hired
1582,861075023930951,SHB5362S,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2020-11-12 19:26:37,Hired
1592,864403045568392,SHB1092Y,"com.ucast.blackbox:1.0.1021.201111_RC,com.grab...",2020-10-12 00:26:32,Hired

In [6]:
#hired & not on v28 and ota client v8
df_smrt[~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) 
        & (df_smrt['Hired Status'] == 'Hired') 
        & ~(df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdmv2:1.0.15', na=False))
        & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdm:1.0.8', na=False))
       ]

,mdt_id,vehicle_id,list_of_app,rpt_time,Hired Status
20,861075023931660,SHD6277M,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-08-01 22:41:25,Hired
194,861075024178717,SHB135P,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-29 16:19:40,Hired
240,861075024163966,SHD6275T,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-29 16:19:09,Hired
750,861075023927411,SHD6417B,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-29 16:12:22,Hired
1372,861075023930167,SHB5805G,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-28 13:36:34,Hired
1375,861075023930415,SHF404S,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-28 10:47:42,Hired
1379,861075024188294,SHB5905B,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-28 04:44:18,Hired
1392,861075023932387,SHB137J,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-26 17:09:55,Hired
1473,864403045574341,SHB1209D,"com.ucast.blackbox:1.0.1017.201029_RC,com.grab...",2021-01-18 15:53:22,Hired

In [7]:
#hired & not on v28 and ota client v7
df_smrt[~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) 
        & (df_smrt['Hired Status'] == 'Hired') 
        & ~(df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdmv2:1.0.15', na=False))
        & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdm:1.0.7', na=False))
       ]
df.to_csv('test.csv', index=False)

In [8]:
#df_smrt['list_of_app'].str.split(',')

In [9]:
df_smrt['list_of_app'][0].split(',')

['com.ucast.blackbox:1.0.1028.201216_RC',
 'com.grab.blackboxtest:1.0',
 'com.ste.itsd.fms.agilmdm:1.0.7',
 'com.grab.tex:20.42.0-522d2fe',
 'com.ucast.blackboxlog:3.0']

In [10]:
#loop through the df and extract only the vehicle and meter/tariff firmware data. exclude the list of software
for i in range(len(df_smrt['list_of_app'])):
    if (df_smrt['Hired Status'][i] == 'Hired') & ('meter.firmware::610' in df_smrt['list_of_app'][i]):
        print(i)
        
#(df_smrt['list_of_app'][i].contains('meter.firmware::610', na=False)) &

'meter.firmware::610' in df_smrt['list_of_app'][1230]

1
3
4
5
6
8
9
11
12
17
18
20
21
32
34
37
41
44
45
47
51
53
54
57
58
59
60
62
63
64
66
67
68
69
70
71
72
73
74
75
76
78
80
81
82
83
84
85
87
88
90
91
92
93
94
95
96
97
98
99
101
102
103
104
105
106
107
108
109
110
111
112
113
115
116
117
118
119
121
123
124
125
126
127
128
129
130
133
134
135
136
137
138
139
140
142
143
144
145
146
147
148
149
150
151
152
154
155
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
181
183
184
185
186
187
188
189
190
192
193
194
195
196
197
199
201
202
203
204
205
206
207
208
209
210
212
213
215
216
217
219
220
221
222
223
224
225
227
228
229
230
231
232
233
235
236
237
238
239
240
241
243
244
245
246
247
248
249
250
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
268
269
270
271
272
274
275
276
277
278
279
280
281
282
283
284
286
287
290
291
292
293
294
295
296
297
298
299
300
301
303
304
305
307
308
309
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
339
340
341
342
343
344
345
346
347
349
350
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
372
373
374
375
377
378
379
380
381
382
383
384
385
386
387
388
389
391
392
393
394
396
397
398
399
400
401
402
405
406
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
468
469
470
471
472
473
474
475
476
478
479
480
481
482
483
484
486
487
488
489
490
491
493
495
496
497
498
499
501
503
504
505
507
508
509
510
511
512
513
514
515
516
517
519
520
521
522
523
524
525
526
527
528
529
530
532
533
534
535
537
538
539
540
543
544
546
547
548
549
550
552
553
555
557
558
559
560
561
562
564
565
566
567
569
570
571
572
573
575
576
577
578
579
580
581
583
584
585
587
588
589
590
591
593
594
595
596
597
598
599
600
601
603
604
605
606
607
608
609
610
613
614
616
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
647
648
650
651
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
673
674
675
677
678
679
681
682
683
684
685
686
687
689
690
691
692
693
694
696
697
698
699
700
701
702
703
704
705
706
708
709
711
713
714
717
718
719
720
722
723
725
727
728
731
733
734
735
736
737
738
739
740
742
743
744
745
746
747
748
749
750
751
752
753
755
756
758
759
760
761
762
764
765
766
768
769
770
771
773
774
775
776
778
779
780
781
782
783
785
786
787
788
789
790
791
792
793
794
795
796
798
799
800
801
802
803
804
806
807
809
810
811
812
814
815
816
817
821
822
823
824
825
826
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
845
846
847
850
851
852
853
854
855
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
879
880
881
882
884
885
886
887
888
889
890
891
892
893
894
895
896
898
900
901
902
904
905
906
908
909
910
911
912
914
915
916
917
918
919
920
921
922
923
925
926
927
928
929
930
932
933
934
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
956
957
958
960
961
962
963
964
965
966
967
969
970
971
972
973
974
975
978
979
980
981
982
983
984
986
987
988
989
991
992
993
994
995
996
997
998
1000
1002
1003
1004
1005
1006
1007
1008
1009
1010
1012
1013
1015
1016
1017
1018
1020
1021
1022
1023
1024
1025
1026
1028
1029
1030
1031
1032
1033
1034
1035
1037
1039
1041
1042
1043
1044
1045
1047
1048
1049
1050
1051
1052
1053
1054
1056
1057
1058
1059
1060
1061
1063
1064
1065
1066
1068
1070
1071
1072
1073
1074
1075
1076
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1093
1094
1095
1096
1097
1100
1101
1102
1103
1105
1107
1110
1111
1112
1113
1114
1115
1117
1118
1119
1120
1121
1123
1124
1125
1126
1128
1129
1130
1131
1132
1134
1135
1136
1137
1138
1139
1141
1142
1143
1144
1145
1147
1149
1150
1151
1152
1154
1155
1157
1158
1159
1160
1161
1162
1164
1165
1166
1167
1169
1170
1171
1172
1174
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1215
1216
1217
1218
1220
1221
1222
1223
1224
1225
1227
1228
1231
1232
1234
1235
1236
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1250
1251
1253
1255
1266
1268
1272
1273
1279
1280
1283
1286
1287
1292
1293
1312
1318
1320
1321
1322
1324
1326
1328
1333
1336
1338
1339
1340
1341
1342
1344
1347
1348
1349
1351
1354
1357
1359
1363
1365
1367
1371
1372
1375
1377
1378
1379
1381
1382
1383
1385
1386
1387
1389
1390
1391
1392
1394
1396
1397
1398
1399
1400
1402
1403
1404
1407
1408
1410
1411
1412
1414
1415
1417
1418
1421
1422
1423
1428
1429
1430
1431
1432
1433
1434
1437
1443
1444
1445
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1473
1474
1475
1476
1477
1479
1481
1483
1484
1485
1486
1487
1488
1489
1490
1492
1493
1494
1495
1498
1499
1500
1502
1509
1511
1512
1513
1514
1515
1516
1525
1526
1528
1532
1534
1548
1549
1551
1582
1592

TypeError: argument of type 'float' is not iterable

In [ ]:
~(df_smrt['list_of_app'].str.contains('com.ucast.blackbox:1.0.1028.201216_RC', na=False)) & (df_smrt['Hired Status'] == 'Hired') & ~(df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdmv2:1.0.15', na=False)) & (df_smrt['list_of_app'].str.contains('com.ste.itsd.fms.agilmdm:1.0.7', na=False))

In [11]:
#filter
df_a = df_smrt[(df_smrt['list_of_app'].str.contains('tariff.firmware', na=False))]

#new dict to store just vehicle and meter/tariff data
vehicle = {}
for i in df_a.index:
    if df_a['list_of_app'][i] == None:
        vehicle[df_a['vehicle_id'][i]] = 'NA'
    else:
        vehicle[df_a['vehicle_id'][i]] = df_a['list_of_app'][i].split(',')[-2:]


df_tariff = pd.DataFrame.from_dict(vehicle, orient='index');
df_tariff
df_tariff.to_csv('tariff.csv')

df_b = df_smrt[(df_smrt['list_of_app'].str.contains('tariff.firmware::24635', na=False))]
df_b

In [ ]:
df_a